# Generated by Django 6.0.3 on 2026-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_profile_address1_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
