# Generated by Django 6.0.3 on 2026-04-26 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 12, 24, 8, 675953, tzinfo=datetime.timezone.utc)),
        ),
    ]
