# Generated by Django 6.0.3 on 2026-04-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cartitem_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='expiry_date',
        ),
    ]
