from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    # path('cart/', views.cart, name='cart'),
    # path('checkout/', views.checkout, name='checkout'),
    # path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    # path('profile/', views.ProfileView.as_view(), name='profile'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    # path('mailerror/', views.MailErrorView.as_view(), name='mailerror'),
    # path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    # path('remove-from-cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    # path('update-cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    # path('submit-review/<int:product_id>/', views.submit_review, name='submit_review'),
    # path('subscribe-newsletter/', views.subscribe_newsletter, name='subscribe_newsletter'),
    # path('add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    # path('remove-from-wishlist/<int:wishlist_item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    # path('process-payment/', views.process_payment, name='process_payment'),
    # path('order-history/', views.order_history, name='order_history'),
    # path('order-detail/<int:order_id>/', views.order_detail, name='order_detail'),
    # path('search/', views.search, name='search'),
    # path('filter/', views.filter_products, name='filter_products'),
    # path('sort/', views.sort_products, name='sort_products'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
    # path('newsletter/', views.NewsletterView.as_view(), name='newsletter'),
    # path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    # path('payment/', views.PaymentView.as_view(), name='payment'),
    # path('order/', views.OrderView.as_view(), name='order'),
    # path('order-item/', views.OrderItemView.as_view(), name='order_item'),
    # path('review/', views.ReviewView.as_view(), name='review'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
]