from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', views.LoginCustomView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add-to-cart/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('password-reset/', PasswordResetView.as_view(template_name='registration_pass/password_reset_form.html', email_template_name='registration_pass/password_reset_email.html', subject_template_name='registration_pass/password_reset_subject.txt'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='registration_pass/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration_pass/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration_pass/password_reset_complete.html'), name='password_reset_complete'),
    path('remove-from-cart/', views.RemoveCartView.as_view(), name='remove_from_cart'),
    path('update-cart/', views.UpdateCartValue.as_view(), name='update_cart'),
    # path('checkout/', views.checkout, name='checkout'),
    # path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/change-password', PasswordChangeView.as_view(template_name='registration_pass/password_change_form.html'), name='password_change'),
    path('profile/change-password-done', PasswordChangeDoneView.as_view(template_name='registration_pass/password_change_done.html'), name='password_change_done'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    # path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    # path('remove-from-cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    # path('update-cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    # path('submit-review/<int:product_id>/', views.submit_review, name='submit_review'),
    # path('subscribe-newsletter/', views.subscribe_newsletter, name='subscribe_newsletter'),
    # path('add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    # path('remove-from-wishlist/<int:wishlist_item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    # path('process-payment/', views.process_payment, name='process_payment'),
    # path('order-history/', views.order_history, name='order_history'),
    # path('order-detail/<int:order_id>/', views.order_detail, name='order_detail'),
    # path('search/', views.search, name='search'),
    # path('filter/', views.filter_products, name='filter_products'),
    # path('sort/', views.sort_products, name='sort_products'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
    # path('newsletter/', views.NewsletterView.as_view(), name='newsletter'),
    # path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    # path('payment/', views.PaymentView.as_view(), name='payment'),
    # path('order/', views.OrderView.as_view(), name='order'),
    # path('order-item/', views.OrderItemView.as_view(), name='order_item'),
    # path('review/', views.ReviewView.as_view(), name='review'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
]